import { Metadata } from "next"
import SideNav from "../components/SideNave"
import HeadBar from "../components/Header"


export const metadata: Metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="flex bg-blue-100">
                <SideNav />
                <HeadBar />
                <div className="p-4 flex-1 lg:ml-[16rem] mt-[8rem]">
                    {children}
                </div>
            </body>
        </html>
    )
}
